const CUSTOMER_ACCOUNT_CREATED=1100
const SELLER_ACCOUNT_CREATED=1101
const COULD_NOT_CREATE_ACCOUNT=1102
const CUSTOMER_ACCOUNT_LOGED_IN=1103
const SELLER_ACCOUNT_LOGED_IN=1104  
const COULD_NOT_LOGED_IN_SELLER_ACCOUNT=1105
const COULD_NOT_LOGED_IN_CUSTOMER_ACCOUNT=1105
export  { 
    CUSTOMER_ACCOUNT_CREATED,
    SELLER_ACCOUNT_CREATED,
    COULD_NOT_CREATE_ACCOUNT,
    CUSTOMER_ACCOUNT_LOGED_IN,
    SELLER_ACCOUNT_LOGED_IN,
    COULD_NOT_LOGED_IN_SELLER_ACCOUNT,
    COULD_NOT_LOGED_IN_CUSTOMER_ACCOUNT
}